widgets:
    -
        type: profile
        position: right 
    -
        type: recent_posts
        position: right
    -
        type: categories
        position: right
    -
        type: tags
        position: right